server:
  port: 8080
spring:
  application:
    name: client-service
  datasource:
    url: jdbc:mysql://autorack.proxy.rlwy.net:13895/railway
    username: root
    password: ovBQjyjkWAndDkAeMpIspSSJWPJiFOmi
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect