server:
  port: 9092

spring:
  application:
    name: inventory-service
  data:
    mongodb:
      uri: mongodb+srv://jawadarbahi001:u5D075UPE6KvQ2wv@cluster0.zdoot.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: inventory
