name: Spring Boot CI Pipeline

on:
  push:
    branches:
      - main  # Trigger on pushes to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Runs the job on the latest Ubuntu image

    strategy:
      matrix:
        service:
          - client-service
          - Inventory-service
          - repas-service  # Add more services here as needed

    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up JDK (Assuming Spring Boot uses Java)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adoptopenjdk'

      # Step 3: Build the specific service using Maven
      - name: Build with Maven for ${{ matrix.service }}
        run: mvn clean install --file BACK-END/${{ matrix.service }}/pom.xml

      # Step 4: Run Tests for the specific service (optional but recommended)
      - name: Run Tests for ${{ matrix.service }}
        run: mvn test --file BACK-END/${{ matrix.service }}/pom.xml
