name: Build and deploy JAR app to Azure Web App - clientser

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures the entire repo is cloned

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: List directories for microservices
        run: |
          echo "Checking for pom.xml in subdirectories"
          dirs=$(find . -type f -name 'pom.xml' -exec dirname {} \;)
          echo "Found directories: $dirs"
          echo "$dirs" > dirs.txt  # Save the directories to a file for use later

      - name: Build each microservice
        run: |
          while read dir; do
            echo "Building project in directory: $dir"
            mvn -f $dir/pom.xml clean install
          done < dirs.txt

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: |
            $(find . -type f -name '*.jar')

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # This is required for requesting the JWT
  
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FDFC386F1C0D4F458686F96C054FC955 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_02BF3C4E7AEE4C11BA2F814850377300 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5F0CE3D2AE3B47889CC998A81DB8D769 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'clientser'
          slot-name: 'Production'
          package: '*.jar'
