name: Publish and Deploy Microservices 🚀

on:
  workflow_dispatch:
  push:
    branches:
    - main

env:
  AZURE_WEBAPP_NAME_SERVICE1: client-service-app
  AZURE_WEBAPP_NAME_SERVICE2: invenroty-service-app
  AZURE_WEBAPP_NAME_SERVICE3: repas-service-app
  DOCKER_IMAGE_NAME_SERVICE1: arb928/client
  DOCKER_IMAGE_NAME_SERVICE2: arb928/inventory
  DOCKER_IMAGE_NAME_SERVICE3: arb928/repas

jobs:
  publish-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Set execute permissions for mvnw
        run: chmod +x ./BACK-END/client-service/mvnw

      - name: Build and Push Docker Image for client
        uses: docker/build-push-action@v4
        with:
          context: ./BACK-END/client-service
          push: true
          tags: ${{ env.DOCKER_IMAGE_NAME_SERVICE1 }}:latest

      - name: Set execute permissions for mvnw
        run: chmod +x ./BACK-END/Inventory-service/mvnw
      
      - name: Build and Push Docker Image for inventory
        uses: docker/build-push-action@v4
        with:
          context: ./BACK-END/Inventory-service
          push: true
          tags: ${{ env.DOCKER_IMAGE_NAME_SERVICE2 }}:latest

      - name: Set execute permissions for mvnw
        run: chmod +x ./BACK-END/repas-service/mvnw
      
      - name: Build and Push Docker Image for repas
        uses: docker/build-push-action@v4
        with:
          context: ./BACK-END/repas-service
          push: true
          tags: ${{ env.DOCKER_IMAGE_NAME_SERVICE3 }}:latest

      # - name: Log in to Azure
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}

      # - name: Deploy client to Azure Web App
      #   uses: azure/webapps-container-deploy@v1
      #   with:
      #     app-name: ${{ env.AZURE_WEBAPP_NAME_SERVICE1 }}
      #     images: ${{ env.DOCKER_IMAGE_NAME_SERVICE1 }}:latest

      # - name: Deploy inventory to Azure Web App
      #   uses: azure/webapps-container-deploy@v1
      #   with:
      #     app-name: ${{ env.AZURE_WEBAPP_NAME_SERVICE2 }}
      #     images: ${{ env.DOCKER_IMAGE_NAME_SERVICE2 }}:latest

      # - name: Deploy repas to Azure Web App
      #   uses: azure/webapps-container-deploy@v1
      #   with:
      #     app-name: ${{ env.AZURE_WEBAPP_NAME_SERVICE3 }}
      #     images: ${{ env.DOCKER_IMAGE_NAME_SERVICE3 }}:latest
