name: Deploy Microservices

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Discover and Build Microservices
      run: |
        for dir in $(find . -name "pom.xml" -exec dirname {} \;); do
          echo "Building and deploying $dir"
          cd $dir
          mvn -B package
          mvn deploy -s $GITHUB_WORKSPACE/settings.xml
          cd -
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
