name: Java CI with Maven

on:
  push:
    branches: 
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - client-service
          - Inventory-service
          - repas-service  # Add more services as necessary

    steps:
      # Step 1: Checkout code from the repository
      - uses: actions/checkout@v4

      # Step 2: Set up JDK 17 using Temurin (formerly AdoptOpenJDK)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'  # Correct distribution
          cache: maven  # Caching for Maven dependencies

      # Step 3: Build each microservice using Maven
      - name: Build with Maven for ${{ matrix.service }}
        run: mvn -B package --file BACK-END/${{ matrix.service }}/pom.xml

      # Optional: Run tests for each service
      - name: Run Tests for ${{ matrix.service }}
        run: mvn test --file BACK-END/${{ matrix.service }}/pom.xml

      # Optional: Upload the dependency graph for better Dependabot alerts
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
